<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'FuseSource' => array($vendorDir . '/fusesource/stomp-php/src/main'),
);
